### ISSUE TITLE
web3.js library is the wrong version

### ISSUE THREAD

**Issue by yacine555** [mjhm/hello_world_dapp#1]
the file index.html is pointing web3.js version 0.x.x. It should point the version 1.0.0.

ie I used the below:
<script src="https://rawgit.com/ethereum/web3.js/1.0/dist/web3.min.js"></script>

**Comment by mjhm** [comment]
@yacine555 Thanks for bringing this up, as I needed to update the version, and I think the `<noscript ...>` tag was misleading so I removed it.

However tricky and not obvious thing about `rawgit` is that it [caches each path permanently](https://github.com/rgrove/rawgit/blob/master/FAQ.md#how-long-does-the-cdn-cache-files-how-can-i-make-it-refresh-my-file)  So the path you have with `.../web3.js/1.0/dist...` will only serve the very first version that it caches with the `1.0` tag.  Newer versions with that tag won't be cached -- so I'm using the exact git hash instead (was for 1.0.0-beta.24, now 1.0.0-beta.26).  Once web3 gets into a post beta release rhythm, using specific versions should work properly.
