### ISSUE TITLE
npm run ganache error

### ISSUE THREAD

**Issue by gofornaman** [mjhm/hello_world_dapp#4]
Hi, I'm trying to run your script on a DigitalOcean droplet. (Ubuntu 16)

When I run npm run ganache, I get this error.

**> @ ganache /home/naman/all-things-dapp/create-react-dapp/mydapp
> ganache-cli

/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:71648
function VM (opts = {}) {
                  ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "ganache"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! @ ganache: `ganache-cli`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ ganache script 'ganache-cli'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ganache-cli
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/naman/all-things-dapp/create-react-dapp/mydapp/npm-debug.log**

Please help me resolve it. Thanks. Btw awesome implementation 💯

**Comment by mjhm** [comment]
It looks like you're using an old node 4.x version which doesn't support the syntax that the program that's tripping up the library.  You probably just need to upgrade it to v8.x. Let me know if that works.

**Comment by gofornaman** [comment]
yes it worked! thanks.
one more thing, will it run on AWS or Digital Ocean droplet?

**Comment by mjhm** [comment]
I don't know any reason it shouldn't, everything is pretty generic.  Though I haven't tried.  Of course on AWS (for example) you'd need to set up a Security Group to open up port 8000 to the internet.
